### PR TITLE
added video_to_images() udf

### PR DESCRIPTION
**Pull request by smellslikeml**
With this udf, we can explode a video to images.

rikai_video_to_images_yt

### CODE REVIEW

**Comment by changhiskhan** [comment]
we may want to add some documentation that this won't work for large videos (or maybe add parameters to control sampling frequency and limit max frames)

**Comment by changhiskhan** [comment]
and maybe add 2 unit tests: 1 for a youtube video path and 1 for a tiny video saved as test data in the repo.

**Comment by changhiskhan** [comment]
otherwise looks great! thanks

**Comment by smellslikeml** [comment]
process_2hour_vid_1hour_sample 
Tested extracting images from the first hour of a 2 hour video on a community databricks cluster and it took 17 mins.
How about `max_images` parameter defaults to extracting roughly 10 min videos filmed at 25 FPS?

**Review by changhiskhan — APPROVED** [review]
lgtm! thanks

**Comment by eddyxu** [comment]
Thanks! Good stuff!

**Pull request merged**
