### PR TITLE
Delete deprecated model attributes: preprocessor, postprocessor

### PR DESCRIPTION
**Pull request by eddyxu**

### CODE REVIEW

**Comment by eddyxu** [comment]
Blocked by #615

**Comment by darcy-shen** [comment]
Is documentation cleanup planned in this PR?

eg. deprecate pre/post processors in https://github.com/eto-ai/rikai/blob/main/docs/sqlml.rst

**Comment by eddyxu** [comment]
Yes,  we'd like to do the doc update here https://github.com/eto-ai/rikai/issues/607

**Comment by darcy-shen** [comment]
I think this pull request is good enough. To avoid potential merge conflicts, I squash and merge it now so that I can create new pull requests without concerns of merge conflicts.

**Pull request merged**
