### PR TITLE
Fix for torch.Tensor.to

### PR DESCRIPTION
**Pull request by da-tubi**
For the yolov5 model, we do not invoke pre_processing. Thus, batch in that case is not a `torch.Tensor`.

The error can be reproducible via https://github.com/da-tubi/rikai-example
```
$ python yolov5_mlflow.py
```

```
21/08/30 14:01:01 ERROR TaskSetManager: Task 0 in stage 0.0 failed 1 times; aborting job
Traceback (most recent call last):
  File "yolov5_mlflow.py", line 59, in <module>
    result.show(1, vertical=False, truncate=False)
  File "/Users/da/.pyenv/versions/rikai-example/lib/python3.8/site-packages/pyspark/sql/dataframe.py", line 486, in show
    print(self._jdf.showString(n, int(truncate), vertical))
  File "/Users/da/.pyenv/versions/rikai-example/lib/python3.8/site-packages/py4j/java_gateway.py", line 1304, in __call__
    return_value = get_return_value(
  File "/Users/da/.pyenv/versions/rikai-example/lib/python3.8/site-packages/pyspark/sql/utils.py", line 117, in deco
    raise converted from None
pyspark.sql.utils.PythonException:
  An exception was thrown from the Python worker. Please see the stack trace below.
Traceback (most recent call last):
  File "/Users/da/.pyenv/versions/3.8.10/envs/rikai-example/lib/python3.8/site-packages/pyspark/python/lib/pyspark.zip/pyspark/worker.py", line 604, in main
    process()
  File "/Users/da/.pyenv/versions/3.8.10/envs/rikai-example/lib/python3.8/site-packages/pyspark/python/lib/pyspark.zip/pyspark/worker.py", line 596, in process
    serializer.dump_stream(out_iter, outfile)
  File "/Users/da/.pyenv/versions/3.8.10/envs/rikai-example/lib/python3.8/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/pandas/serializers.py", line 273, in dump_stream
    return ArrowStreamSerializer.dump_stream(self, init_stream_yield_batches(), stream)
  File "/Users/da/.pyenv/versions/3.8.10/envs/rikai-example/lib/python3.8/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/pandas/serializers.py", line 81, in dump_stream
    for batch in iterator:
  File "/Users/da/.pyenv/versions/3.8.10/envs/rikai-example/lib/python3.8/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/pandas/serializers.py", line 266, in init_stream_yield_batches
    for series in iterator:
  File "/Users/da/.pyenv/versions/3.8.10/envs/rikai-example/lib/python3.8/site-packages/pyspark/python/lib/pyspark.zip/pyspark/worker.py", line 356, in func
    for result_batch, result_type in result_iter:
  File "/Users/da/.pyenv/versions/rikai-example/lib/python3.8/site-packages/rikai/spark/sql/codegen/pytorch.py", line 74, in torch_inference_udf
    batch = batch.to(device)
AttributeError: 'list' object has no attribute 'to'
```

### CODE REVIEW

**Comment by da-tubi** [comment]
For GPU:
https://github.com/fcakyon/yolov5-pip/blob/4aaf354d8a7f66bb8baa4e5ba73e83b960d8f2d1/yolov5/models/common.py#L330-331

**Comment by da-tubi** [comment]
I tried to split

https://github.com/fcakyon/yolov5-pip/blob/4aaf354d8a7f66bb8baa4e5ba73e83b960d8f2d1/yolov5/models/common.py#L291

into pre_processing and post_processing but failed because there are dependencies on the model for pre_processing and post_processing.

**Comment by da-tubi** [comment]
Here are steps to test this PR with GPU:

```
git clone https://github.com/da-tubi/rikai-example.git
cd rikai-example
pip install -r requirements.txt
```

**Review by changhiskhan — APPROVED** [review]
Can you please look into why the `batch` is coming out of the DataLoader as a list? If `batch_size>0` does DataLoader return a list of Tensor or a higher dim Tensor?

**Comment by da-tubi** [comment]
https://github.com/ultralytics/yolov5/blob/fad57c29cd27c0fcbc0038b7b7312b9b6ef922a8/models/common.py#L292

Because yolov5's AutoShape:
For Tensor input, it returns with a raw tensor:
https://github.com/ultralytics/yolov5/blob/fad57c29cd27c0fcbc0038b7b7312b9b6ef922a8/models/common.py#L306

For other inputs, it do complicated pre-processing and post-processing:
+ Pre: https://github.com/ultralytics/yolov5/blob/fad57c29cd27c0fcbc0038b7b7312b9b6ef922a8/models/common.py#L308
+ Post: https://github.com/ultralytics/yolov5/blob/fad57c29cd27c0fcbc0038b7b7312b9b6ef922a8/models/common.py#L339

**Pull request merged**
