### PR TITLE
udf: array_box2d

### PR DESCRIPTION
**Pull request by da-tubi**
Demo usage of `array_box2d`: https://github.com/da-tubi/rikai-example/blob/54ce6f71e12be369b3bbd197d34f034e2d01d141/elephants_dream.ipynb

### CODE REVIEW

**Comment by changhiskhan** [comment]
Looking at the notebook you're using this udf to convert the ML_PREDICT output into Rikai types. Why not do that in the `post_processing`?

The major question here is how do we provide a generalized mechanism to convert to Rikai types. Do we want to have a `array_<rikai type>` udf for every Rikai type? Typically when/how are we expecting our users to do the type conversion themselves?

**Comment by eddyxu** [comment]
Can we use standard spark sql function instead?

https://spark.apache.org/docs/latest/api/sql/index.html#transform

```sql
SELECT transform(boxes, b -> box2d(b)) FROM ...
```

**Comment by da-tubi** [comment]
Neither `ML_PREDICT` nor `TRANSFORM` supports UDT as the return data type.

**Comment by da-tubi** [comment]
> Can we use standard spark sql function instead?

No. The reason is listed above.

**Comment by eddyxu** [comment]
Shall we fix `ML_PREDICT` **AND** `TRANSFORM` then?

**Comment by eddyxu** [comment]
This is the fix for `ML_PREDICT` 

https://github.com/eto-ai/rikai/pull/448

**Pull request closed without merging**
